services:
  advanced_api:
    container_name: inventory-management-api
    image: 
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV} 
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}